name = "pg1-ai-agent-worker"
main = "workers/index.js"
compatibility_date = "2026-09-01"
compatibility_flags = ["nodejs_compat"]
account_id = "f4ca340d9bcbeeab89bba95915dd072e"

[assets]
directory = "./"
binding = "ASSETS"

[[r2_buckets]]
binding = "STORAGE_BUCKET"
bucket_name = "pg1-storage"

[vars]
ENVIRONMENT = "production"
