-- agent_telemetry: bring the table to exactly the shape lib/telemetry.mjs
-- writes and lib/usageStats.mjs reads, whatever shape it is in now.
--
-- Why: the live table was created by hand before 20261005120000 and never
-- matched it (no event_type, no latency_ms, no check constraints, one
-- extra column), so `create table if not exists` there was a no-op and
-- every PostgREST insert from lib/telemetry.mjs failed with a missing
-- column. This migration reconciles any starting shape - that live one,
-- the part-1 shape, or no table at all - and is safe to run repeatedly.
--
-- Target shape (lib/telemetry.mjs buildTelemetryRow + the generated id):
--   id             bigint identity primary key (an existing uuid/int id is kept)
--   created_at     timestamptz not null default now()
--   event_type     text not null default 'tool_call'  ('tool_call' | 'settlement' | 'initialize')
--   endpoint       text not null                      (the route, e.g. /api/mcp)
--   tool_name      text
--   payment_type   text not null default 'none'       ('free' | 'free_tier' | 'license' | 'x402' | 'none')
--   status         text not null
--   latency_ms     integer, >= 0
--   client_name    text, <= 64 chars                  (MCP initialize clientInfo, sanitised)
--   client_version text, <= 32 chars
--   caller_hash    text, 32 lowercase hex             (salted HMAC of the caller IP, never the IP)
--   is_fixture     boolean not null default false
-- Any other column is left in place but made nullable, so it can never
-- block an insert that does not name it.
--
-- Rows hold no message contents, tool arguments, wallet addresses, domains
-- or other values a caller queried. Rows older than 90 days are deleted
-- daily by the /api/errors/cleanup cron (lib/telemetry.mjs
-- purgeExpiredTelemetry).
--
-- Access: service role only. RLS on, nothing granted to anon or
-- authenticated (every read and write goes through the service-role key).
--
-- Type changes use plain casts. The live table has no rows; on a table with
-- rows a value that cannot be cast fails the whole migration (it runs in
-- one transaction) rather than losing data.

create table if not exists public.agent_telemetry (
  id bigint generated always as identity primary key,
  created_at timestamptz not null default now()
);

-- 1. Every column the code needs.
alter table public.agent_telemetry
  add column if not exists created_at timestamptz,
  add column if not exists event_type text,
  add column if not exists endpoint text,
  add column if not exists tool_name text,
  add column if not exists payment_type text,
  add column if not exists status text,
  add column if not exists latency_ms integer,
  add column if not exists client_name text,
  add column if not exists client_version text,
  add column if not exists caller_hash text,
  add column if not exists is_fixture boolean;

-- 2. id: kept if it already works as a generated key; otherwise made one.
do $$
declare
  id_type text;
  id_default text;
  id_identity text;
  has_pk boolean;
begin
  select c.data_type, c.column_default, c.is_identity
    into id_type, id_default, id_identity
    from information_schema.columns c
   where c.table_schema = 'public' and c.table_name = 'agent_telemetry' and c.column_name = 'id';

  if id_type is null then
    alter table public.agent_telemetry add column id bigint generated always as identity;
  elsif id_identity = 'NO' and id_default is null then
    if id_type in ('bigint', 'integer', 'smallint') then
      alter table public.agent_telemetry alter column id set not null;
      execute 'alter table public.agent_telemetry alter column id add generated by default as identity';
    elsif id_type = 'uuid' then
      alter table public.agent_telemetry alter column id set default gen_random_uuid();
    else
      raise exception 'agent_telemetry.id has type % with no default; cannot make it a generated key', id_type;
    end if;
  end if;

  select exists (
    select 1 from pg_constraint
     where conrelid = 'public.agent_telemetry'::regclass and contype = 'p'
  ) into has_pk;
  if not has_pk then
    alter table public.agent_telemetry add primary key (id);
  end if;
end $$;

-- 3. Column types the code relies on (no-op when already right).
do $$
declare
  want record;
  have text;
begin
  for want in
    select * from (values
      ('created_at', 'timestamp with time zone', 'timestamptz'),
      ('event_type', 'text', 'text'),
      ('endpoint', 'text', 'text'),
      ('tool_name', 'text', 'text'),
      ('payment_type', 'text', 'text'),
      ('status', 'text', 'text'),
      ('latency_ms', 'integer', 'integer'),
      ('client_name', 'text', 'text'),
      ('client_version', 'text', 'text'),
      ('caller_hash', 'text', 'text'),
      ('is_fixture', 'boolean', 'boolean')
    ) as t(col, info_type, sql_type)
  loop
    select c.data_type into have
      from information_schema.columns c
     where c.table_schema = 'public' and c.table_name = 'agent_telemetry' and c.column_name = want.col;
    if have is distinct from want.info_type then
      if want.col = 'created_at' and have = 'timestamp without time zone' then
        execute 'alter table public.agent_telemetry alter column created_at type timestamptz using created_at at time zone ''UTC''';
      else
        execute format('alter table public.agent_telemetry alter column %I type %s using %I::%s', want.col, want.sql_type, want.col, want.sql_type);
      end if;
    end if;
  end loop;
end $$;

-- 4. Defaults, then fill any nulls (none on the live table) before NOT NULL.
alter table public.agent_telemetry
  alter column created_at set default now(),
  alter column event_type set default 'tool_call',
  alter column payment_type set default 'none',
  alter column is_fixture set default false;

update public.agent_telemetry set created_at = now() where created_at is null;
update public.agent_telemetry set event_type = 'tool_call' where event_type is null;
update public.agent_telemetry set endpoint = 'unknown' where endpoint is null;
update public.agent_telemetry set payment_type = 'none' where payment_type is null;
update public.agent_telemetry set status = 'unknown' where status is null;
update public.agent_telemetry set is_fixture = false where is_fixture is null;

alter table public.agent_telemetry
  alter column created_at set not null,
  alter column event_type set not null,
  alter column endpoint set not null,
  alter column payment_type set not null,
  alter column status set not null,
  alter column is_fixture set not null,
  alter column tool_name drop not null,
  alter column latency_ms drop not null,
  alter column client_name drop not null,
  alter column client_version drop not null,
  alter column caller_hash drop not null;

-- 5. Columns the code does not know about must never block an insert:
-- a NOT NULL column without a default is made nullable (kept, not dropped).
do $$
declare
  extra record;
begin
  for extra in
    select c.column_name
      from information_schema.columns c
     where c.table_schema = 'public' and c.table_name = 'agent_telemetry'
       and c.column_name not in ('id', 'created_at', 'event_type', 'endpoint', 'tool_name', 'payment_type', 'status',
                                 'latency_ms', 'client_name', 'client_version', 'caller_hash', 'is_fixture')
       and c.is_nullable = 'NO' and c.column_default is null
       and c.is_identity = 'NO' and c.is_generated = 'NEVER'
  loop
    execute format('alter table public.agent_telemetry alter column %I drop not null', extra.column_name);
    raise notice 'agent_telemetry.% made nullable: lib/telemetry.mjs does not write it', extra.column_name;
  end loop;
end $$;

-- 6. Check constraints, by name, replacing part 1's inline ones.
alter table public.agent_telemetry drop constraint if exists agent_telemetry_event_type_check;
alter table public.agent_telemetry drop constraint if exists agent_telemetry_payment_type_check;
alter table public.agent_telemetry drop constraint if exists agent_telemetry_latency_ms_check;
alter table public.agent_telemetry drop constraint if exists agent_telemetry_client_name_check;
alter table public.agent_telemetry drop constraint if exists agent_telemetry_client_version_check;
alter table public.agent_telemetry drop constraint if exists agent_telemetry_caller_hash_check;

alter table public.agent_telemetry
  add constraint agent_telemetry_event_type_check
    check (event_type in ('tool_call', 'settlement', 'initialize')),
  add constraint agent_telemetry_payment_type_check
    check (payment_type in ('free', 'free_tier', 'license', 'x402', 'none')),
  add constraint agent_telemetry_latency_ms_check
    check (latency_ms is null or latency_ms >= 0),
  add constraint agent_telemetry_client_name_check
    check (client_name is null or char_length(client_name) <= 64),
  add constraint agent_telemetry_client_version_check
    check (client_version is null or char_length(client_version) <= 32),
  add constraint agent_telemetry_caller_hash_check
    check (caller_hash is null or caller_hash ~ '^[0-9a-f]{32}$');

-- 7. Indexes: newest-first reads and the retention delete, per-tool
-- rollups, and the stats read's is_fixture = false + created_at window.
create index if not exists agent_telemetry_created_at_idx
  on public.agent_telemetry (created_at desc);
create index if not exists agent_telemetry_tool_created_at_idx
  on public.agent_telemetry (tool_name, created_at desc);
create index if not exists agent_telemetry_fixture_created_at_idx
  on public.agent_telemetry (is_fixture, created_at desc);

-- 8. Service role only, same as public.pg1_errors and public.pg1_handoffs.
alter table public.agent_telemetry enable row level security;
revoke all on public.agent_telemetry from public, anon, authenticated;

do $$
declare
  seq text := pg_get_serial_sequence('public.agent_telemetry', 'id');
begin
  if seq is not null then
    execute format('revoke all on sequence %s from public, anon, authenticated', seq);
  end if;
end $$;

-- 9. Let PostgREST see the new columns now rather than on its next reload.
notify pgrst, 'reload schema';
